server {
    listen 80;
    server_name urna-seca.vvsistemas.com.br;

    # O diretório onde faremos o build (adicione o caminho absoluto do servidor aqui)
    root /home/vini/VVSISTEMAS/urna_ceca/urna/dist;
    index index.html;

    location / {
        # O SPA Routing precisa que tudo redirecione para o index.html
        try_files $uri $uri/ /index.html;
    }

    # Desabilitar cache para o index.html principal
    location ~* \.html$ {
        expires -1;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    # Habilitar cache para arquivos estáticos gerados pelo Vite (js, css, imagens)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|wav|mp3)$ {
        expires max;
        add_header Cache-Control "public, max-age=31536000, immutable";
        access_log off;
    }

    # Logs de acesso e erro específicos para facilitar troubleshooting
    error_log /var/log/nginx/urna_error.log;
    access_log /var/log/nginx/urna_access.log;
}
